# General
name: Random Thoughts
description: "Tech, Science, Experience."
url: http://localhost:4000

markdown: kramdown
highlighter: rouge

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: yourusername
twitter: twitter.com/ebeid_elsayed
github: github.com/ebeid
linkedin: linkedin.com/in/ebeidelsayed

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
