baseurl: 'https://ebeid.github.io'
languageCode: en-US
title: Ebeid ElSayed
disqusShortname: ''
googleAnalytics: ''
theme: hugo-sustain
publishDir: docs
permalinks:
  post: '/:year/:month/:day/:slug'
params:
  avatar: profile.png
  author: Ebeid ElSayed
  description: Ebeid's website
  custom_css: []
  custom_js: []
  social:
    Github: ebeid
    Email: ebeidse2@illinois.edu
    Twitter: ebeidelsayed
    LinkedIn: ebeidelsayed
    Stackoverflow: users/1779039/ebeid-elsayed
menu:
  main:
    - name: blog
      weight: 100
      identifier: blog
      url: /blog/
    - name: projects
      identifier: projects
      weight: 200
      url: /projects/
    - name: resume
      identifier: resume
      weight: 300
      url: /resume/resume.pdf
